pluginManagement {
    repositories {
        mavenCentral()
        maven { url = "https://plugins.gradle.org/m2/" }
        gradlePluginPortal()
    }

    plugins {
        id 'uk.gov.justice.service.laa.laa-spring-boot-gradle-plugin' version '3.0.1'
        id 'org.openapi.generator' version '7.23.0'
        id 'io.freefair.lombok' version '9.4.0'
    }
}

rootProject.name = 'laa-spring-boot-microservice-template'

include 'spring-boot-microservice-api'
include 'spring-boot-microservice-service'
