spring:
  application:
    name: LAA Spring Boot Microservice

  # example database
  datasource:
    url: jdbc:h2:mem:itemsDb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true

  #do not auto create db schema, use .sql scripts
  jpa:
    hibernate:
      ddl-auto: none

management:
  # specify actuator endpoints to enable
  endpoints:
    web:
      exposure:
        include: health

sentry:
  dsn: # configure dsn url here
  environment: # configure environment name here