name: Build feature branch

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  JDK_DISTRIBUTION: &JDK_DISTRIBUTION 'corretto'

jobs:
  build-and-test:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@4daa796eff475c7a107e17daf4e4882b8a1b949b # v2.3.0
    permissions:
      contents: write
      packages: write
    with:
      java_distribution: *JDK_DISTRIBUTION
      integration_test_task: "integrationTest"
      release_type: 'snapshot'
      jacoco_coverage_report: 'true'
      jacoco_coverage_report_path: 'spring-boot-microservice-service/build/reports/jacoco'
      junit_results_path: 'spring-boot-microservice-service/build/test-results'
      junit_report_path: 'spring-boot-microservice-service/build/reports/tests'
      checkstyle_report_path: 'spring-boot-microservice-service/build/reports/checkstyle'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}

  ecr-publish-service-image:
    if: false # Enable once ECR repository and Kubernetes namespace are configured
    needs: [ build-and-test ]
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/ecr-publish-image.yml@4daa796eff475c7a107e17daf4e4882b8a1b949b # v2.3.0
    permissions:
      contents: read
      id-token: write
      security-events: write
    with:
      java_distribution: *JDK_DISTRIBUTION
      dockerfile_path: Dockerfile
      image_version: ${{ needs.build-and-test.outputs.published_artifact_version }}
      image_scan: 'true'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      ecr_repository: ${{ vars.ECR_REPOSITORY }}
      ecr_region: ${{ vars.ECR_REGION }}
      ecr_role_to_assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
      snyk_token: ${{ secrets.SNYK_TOKEN }}

  vulnerability-scan-app:
    runs-on: ubuntu-latest
    needs: [ build-and-test ]
    permissions:
      contents: read
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SNYK_TEST_EXCLUDE: build,generated
      SNYK_TARGET_REFERENCE: main
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run Snyk to check app for vulnerabilities
        uses: snyk/actions/gradle@9adf32b1121593767fc3c057af55b55db032dc04 #master
        with:
          command: code test
          args: --severity-threshold=high
