name: Tag and deploy

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  define-image-tag:
    runs-on: ubuntu-latest
    outputs:
      repo_name: ${{ steps.extract_repo_name.outputs.repo_name }}
    steps:
      - name: Extract short repo name
        shell: bash
        run: echo "repo_name=${GITHUB_REPOSITORY#*\/laa-spring-boot-}" >> $GITHUB_OUTPUT
        id: extract_repo_name

  assemble-publish:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.capture_version.outputs.app_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew assemble
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Capture version
        shell: bash
        id: capture_version
        run: |
          VERSION=$(grep "version=" gradle.properties | cut -d'=' -f2)
          echo "app_version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Captured version: $VERSION"

      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload jarfile
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-microservice-api-jar
          path: spring-boot-microservice-service/build/libs/spring-boot-microservice-service-${{ steps.capture_version.outputs.app_version }}.jar

  ecr:
    needs: [assemble-publish, define-image-tag]
    runs-on: ubuntu-latest
    permissions:
      id-token: write # for requesting jwt
      contents: read  # for actions/checkout
    steps:
      # Checkout github repo
      - uses: actions/checkout@v4
      # Assume role in cloud platform
      - name: download jar
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-microservice-api-jar

#      - name: Configure aws credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
#          aws-region: ${{ vars.ECR_REGION }}
#
#      - name: Login ecr
#        uses: aws-actions/amazon-ecr-login@v2
#        id: login-ecr
#
      # Build and push docker image to container repo
      - name: docker build and push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          REPO_NAME: ${{ needs.define-image-tag.outputs.repo_name }}
          APP_VERSION: ${{ needs.assemble-publish.outputs.app_version }}
        run: |
          echo "Captured version: ${{ env.APP_VERSION }}"
          docker build --build-arg app_version=${{ env.APP_VERSION }} -t $REGISTRY/$REPOSITORY:${{ env.REPO_NAME }}-${{ env.APP_VERSION }} .
#          docker push $REGISTRY/$REPOSITORY:${{ env.REPO_NAME }}-${{ env.APP_VERSION }}

      - name: delete artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: spring-boot-microservice-api-jar
